server {
  listen 80;
  client_max_body_size 1m;

  location = /health {
    access_log off;
    return 200 'ok';
    add_header Content-Type text/plain;
  }

  location /api/orders {
    proxy_pass http://order-service:8081/orders;
    proxy_set_header X-Demo-User $http_x_demo_user;
    proxy_set_header X-Demo-Role $http_x_demo_role;
    proxy_set_header X-Correlation-Id $http_x_correlation_id;
  }

  location /api/write/ {
    proxy_pass http://lucky-draw-write:8082/;
    proxy_set_header X-Demo-User $http_x_demo_user;
    proxy_set_header X-Demo-Role $http_x_demo_role;
    proxy_set_header X-Correlation-Id $http_x_correlation_id;
  }

  location /api/analytics/ {
    proxy_pass http://analytics-service:8085/;
    proxy_set_header X-Demo-User $http_x_demo_user;
    proxy_set_header X-Demo-Role $http_x_demo_role;
  }

  location /api/notifications {
    proxy_pass http://notification-service:8086/notifications;
    proxy_set_header X-Demo-User $http_x_demo_user;
    proxy_set_header X-Demo-Role $http_x_demo_role;
  }

  location /api/rewards {
    proxy_pass http://reward-service:8087/rewards;
    proxy_set_header X-Demo-User $http_x_demo_user;
    proxy_set_header X-Demo-Role $http_x_demo_role;
  }

  location / {
    proxy_pass http://frontend:80;
    proxy_set_header Host $host;
  }
}

